name: Documentation Generation with Sphinx

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
      - name: Build Documentation
        run: |
          sphinx-build -b html docs/ docs/_build
